// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace OwnedEntityType.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230301175403_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.HasKey("ID");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Person", b =>
                {
                    b.OwnsMany("Order", "Orders", b1 =>
                        {
                            b1.Property<int>("ID")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("ID"));

                            b1.Property<int>("Fiyat")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Fiyat");

                            b1.Property<int>("OwnedEmpoyeeID")
                                .HasColumnType("int");

                            b1.Property<string>("Urun")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("UrunAdi");

                            b1.HasKey("ID");

                            b1.HasIndex("OwnedEmpoyeeID");

                            b1.ToTable("Order");

                            b1.WithOwner()
                                .HasForeignKey("OwnedEmpoyeeID");
                        });

                    b.OwnsOne("PersonelDigerbilgiler", "PersonelDigerbilgiler", b1 =>
                        {
                            b1.Property<int>("PersonID")
                                .HasColumnType("int");

                            b1.Property<string>("Adres")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Departman")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PersonID");

                            b1.ToTable("Persons");

                            b1.WithOwner()
                                .HasForeignKey("PersonID");
                        });

                    b.Navigation("Orders");

                    b.Navigation("PersonelDigerbilgiler");
                });
#pragma warning restore 612, 618
        }
    }
}
